"""empty message

Revision ID: 26c5ee45d80a
Revises: 
Create Date: 2023-12-13 15:00:52.752233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c5ee45d80a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('interest_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('classic', sa.Boolean(), nullable=True),
    sa.Column('jazz', sa.Boolean(), nullable=True),
    sa.Column('pop', sa.Boolean(), nullable=True),
    sa.Column('ballade', sa.Boolean(), nullable=True),
    sa.Column('hiphop', sa.Boolean(), nullable=True),
    sa.Column('reggae', sa.Boolean(), nullable=True),
    sa.Column('trot', sa.Boolean(), nullable=True),
    sa.Column('electronic', sa.Boolean(), nullable=True),
    sa.Column('rock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interest_info')
    op.drop_table('user')
    # ### end Alembic commands ###
