"""empty message

Revision ID: 48788c6d986a
Revises: d39c5439d56d
Create Date: 2023-12-14 09:56:03.566542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48788c6d986a'
down_revision = 'd39c5439d56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
